version: '2'
services:
  db:
    container_name: shop.db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    container_name: shop.web
    build: ./MyShop
    depends_on:
      - db
    links:
      - db
  
  reverse-proxy:
    container_name: shop.proxy
    image: nginx
    depends_on:
      - web
    ports:
      - "80:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
