version: '2'
services:

  web:
    container_name: shop.web
    build: 
      context: .
      dockerfile: ./MyShop/Dockerfile

  backend:
    container_name: shop.backend
    build:
      context: .
      dockerfile: ./Backend/Dockerfile

  sss:
    container_name: shop.sss
    build: ./StorageService
    volumes:
      - ./proxy.conf:/app
  
  reverse-proxy:
    container_name: shop.proxy
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./images:/app/storage_service/wwwroot/images
